-- INSERT INTO product(ID, name, catID) VALUES(1, 'Apples', 1)
-- INSERT INTO product(ID, name, catID) VALUES(2, 'Oranges', 1)
-- INSERT INTO product(ID, name, catID) VALUES(3, 'Bananas', 1)
-- INSERT INTO product(ID, name, catID) VALUES(4, 'Carrots',2)